[ADD] fix problème indentation

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -13,68 +13,106 @@ env:
   EXECUTABLES: "exec"
 
 jobs:
-  check_coding_style:
-    name: Check Coding Style
+  no_test_jobs:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
+      - name: Checkout GH repository
         uses: actions/checkout@master
-
-      - name: Run Coding Style Checker
+        with:
+          repository: ' '
+      - name: No test jobs
         run: |
-          docker run --rm -v ${{ github.workspace }}:/workspace ghcr.io/epitech/coding-style-checker:latest check.sh
-          $(pwd) $(pwd)
+          if [[ "${{ github.repository }}" == "EpitechPromo2028/B-DOP-200-BDX-2-1-chocolatine-faris.khsime" ]]; then
+            echo "No test are run in this job. It stops immediately"
+            exit 1
+          else
+            exit 0
+          fi
 
-  Checking_program_compilation:
-    needs: check_coding_style
-    name: Checking Program Compilation
-    runs-on: epitechcontent/epitest-docker
-    timeout-minutes: 5
+  check_coding_style:
+    needs: no_test_jobs
+    runs-on: ubuntu-latest
+    container: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: Checkout Repository
+      - name: Checkout GH repository
         uses: actions/checkout@master
+        with:
+          repository: ' '
 
-      - name: Compile with Make
-        run: make
-        timeout-minutes: 2
+      - name: Run coding-style checker script
+        run: check.sh $(pwd) $(pwd)
 
-      - name: Clean repository
-        run: make clean
-
-      - name: Check Executables
+      - name: Display coding style errors as annotations if any errors
+        id: annotations
         run: |
-          IFS=',' read -ra EXECS <<< "${EXECUTABLES}"
-          for EXEC in "${EXECS[@]}"; do
-            if [ ! -x "./$EXEC" ]; then
-              echo "Error: $EXEC not found or not executable"
+          NB_ERRORS=$(car coding-style-reports.log | wc -l)
+          if [ $NB_ERRORS -ge 1 ]; then
+            while IFS= read -r line; do
+              FILE=$(echo $line | cut -d ':' -f1)
+              FILE=$(realpath --relative-to=$(pwd) $FILE)
+              LINE=$(echo $line | cut -d ':' -f2)
+              ERROR=$(echo $line | cut -d ':' -f3-)
+              echo "::error file=$FILE,line=$LINE,title=$NB_ERRORS coding style errors found::$ERROR"
+            done < coding-style-reports.log
+            exit 1
+          fi
+          exit 0
+
+
+  Check_program_compilation:
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    container: epitechcontent/epitest-docker:latest
+    needs: check_coding_style
+    steps:
+
+      - name: Chekout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ' '
+
+      - name: Compile repository
+        run: make
+      - name: Check file
+        run: |
+          for file in $EXECUTABLES;do
+            if [ ! -x "$file" ]; then
+              echo "File $file does not exist or is not executable"
               exit 1
             fi
           done
 
-  run-tests:
-    needs: Checking_program_compilation
-    name: Run Tests
-    runs-on: epitechcontent/epitest-docker
-    timeout-minutes: 5
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@master
+      - name: Clean repository
+        run: make fclean
 
-      - name: Run Tests
+  run_tests:
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    container: epitechcontent/epitest-docker:latest
+    needs: Check_program_compilation
+    steps:
+
+      - name: Chekout GH repository
+        uses: actions/checkout@master
+        with:
+          repository: ' '
+
+      - name: Compile tests binaries
         run: make tests_run
-        timeout-minutes: 2
 
   push_to_mirror:
-    needs: run-tests
-    name: Pushing to mirror repository
     runs-on: ubuntu-latest
+    needs: run_tests
     if: github.event_name == 'push'
     steps:
-      - name: Checkout GH repo
+      - name: Checkout GH repository
         uses: actions/checkout@master
-
-      - name: Push to mirror
-        uses: pixta-dev/repository-mirroring-action@v1
         with:
-          repo_url: ${{ env.MIRROR_URL }}
-          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+          fetch-depth: 0
+      - name: Push to mirror
+        uses: pixta-dev/repository-mirroring-action@v1.1.1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
